<?php
/**
 * Created by PhpStorm.
 * User: marko
 * Date: 3.11.16.
 * Time: 13.13
 */

namespace App\MateyModels;


use App\MateyModels\Activity;
use App\MateyModels\User;
use App\Services\BaseService;
use Doctrine\DBAL\Connection;
use Predis\Client;

class ActivityManager extends AbstractManager
{

    public function readModelBy(array $criteria, array $orderBy = null,
                                $limit = null, $offset = null, array $fields = null)
    {
        if(!isset($criteria['deleted'])) $criteria['deleted'] = 0;
        return parent::readModelBy($criteria, $orderBy, $limit, $offset, $fields); // TODO: Change the autogenerated stub
    }

}